### PR TITLE
Make unsplit packages unless necessary

### PR DESCRIPTION
**Pull request by hseg**
Template currently makes split packages containing 1/2 packages, making the output needlessly complex.
Instead, only split if `--mult` is passed.

Conceptually, this does not depend on #29, but I'd rather not have to rebase it on top if they're both accepted.

### CODE REVIEW

**Comment by wenLiangcan** [comment]
@hseg Could you help on testing this change by `Python2`? I just fixed two compatibility issues of your last PR .   

f91604a94d8d3f7510913b5bbc28986cb36910c1   
cad02932f19e139e159bee62f5478aaf03fcf9df

**Comment by hseg** [comment]
On Wed, Feb 21, 2024 at 07:54:05AM -0800, 尹良灿 wrote:
> @hseg Could you help on testing this change by `Python2`? I just fixed two compatibility issues of your last PR .   
> 
> f91604a94d8d3f7510913b5bbc28986cb36910c1   
> cad02932f19e139e159bee62f5478aaf03fcf9df

OK, though you do know that Python 2 has been EOL for three years now, right?
Checking with `python2 pip2pkgbuild/pip2pkgbuild.py -o pip` on HEAD, am seeing
no errors, what codepaths do you still want me to test?

**Comment by hseg** [comment]
On Wed, Feb 21, 2024 at 07:54:05AM -0800, 尹良灿 wrote:
> @hseg Could you help on testing this change by `Python2`? I just fixed two compatibility issues of your last PR .   
> 
> f91604a94d8d3f7510913b5bbc28986cb36910c1   
> cad02932f19e139e159bee62f5478aaf03fcf9df

Ah oops, was testing HEAD, not the PR

**Comment by hseg** [comment]
Hey, any progress with this PR? Only #34 has been opened thinking it doesn't exist, and my fix to #32 makes a little less sense if we're still making split packages by default.

**Comment by hseg** [comment]
(Just double-checked and `python2 pip2pkgbuild.py -o pip` works fine. If you have further checks you want before merging, please speak up)

**Pull request merged**
